#!/bin/bash
whoami | ( wc -c | xargs -I {} sh -c 'echo ${}'  # Capture character count) | while IFS= read -r char_count; do echo -e "[Got]\n\n(0 chars long)\n\n[Expected]\nroot\n\n(5 chars long)" echo -e "(${char_count} chars long)" done
